In [1]:
from pyspark.sql import SparkSession
import numpy as np
import pandas as pd

spark = SparkSession.builder.master("local[2]")\
                            .appName("COM6012 Assignment Question——2")\
                            .config("spark.driver.memory", "8g")\
                            .getOrCreate()


In [3]:
raw_df = pd.read_csv('./Dataset/ClaimPredictionChallenge/train_set.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:

pd.set_option('display.max_columns', None)
raw_df.head(5)
print(raw_df.shape)

(13184290, 35)


In [5]:
raw_df.head(5)

Row_ID  Household_ID  Vehicle  Calendar_Year  Model_Year Blind_Make  \
0       1             1        3           2005        2005          K   
1       2             2        2           2005        2003          Q   
2       3             3        1           2005        1998         AR   
3       4             3        1           2006        1998         AR   
4       5             3        2           2005        2001          D   

  Blind_Model Blind_Submodel Cat1 Cat2 Cat3 Cat4 Cat5 Cat6 Cat7 Cat8 Cat9  \
0        K.78         K.78.2    D    C    F    ?    ?    C    ?    C    A   
1        Q.22         Q.22.3    B    C    A    A    A    E    C    A    B   
2       AR.41        AR.41.1    B    ?    A    A    A    C    C    A    B   
3       AR.41        AR.41.1    B    ?    A    A    A    C    C    A    B   
4        D.20         D.20.0    J    C    B    ?    ?    D    ?    A    B   

  Cat10 Cat11 Cat12 OrdCat      Var1      Var2      Var3      Var4      Var5  \
0     B     F     D      4  1.270533  0.999418  0.588154  0.908351  1.008912   
1     A     B     D      5  0.217951  0.567140  1.421206  0.485509  1.240851   
2     A     E     D      2 -0.754282 -1.646127 -1.101091 -1.679445 -0.971487   
3     B     B     B      2 -0.754282 -1.646127 -1.101091 -1.679445 -0.971487   
4     A     B     B      5  0.563454  1.863975  1.814591  1.838605  0.812656   

       Var6      Var7      Var8 NVCat   NVVar1    NVVar2    NVVar3    NVVar4  \
0  0.261040  0.907793 -0.077998     M -0.23153 -0.266117 -0.272337 -0.251419   
1  0.432987 -0.726459  0.204785     O -0.23153 -0.266117 -0.272337 -0.251419   
2 -1.405797 -0.837048 -1.176858     F -0.23153 -0.266117 -0.272337 -0.251419   
3 -1.405797 -0.837048 -1.176858     F -0.23153 -0.266117 -0.272337 -0.251419   
4  2.112691  1.534462  2.347260     F -0.23153 -0.266117 -0.272337 -0.251419   

   Claim_Amount  
0           0.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0

In [6]:
raw_df[(raw_df.Cat1 == '?')]

Row_ID  Household_ID  Vehicle  Calendar_Year  Model_Year  \
274            275           131        1           2005        1995   
673            674           357        1           2005        1996   
678            679           359        2           2005        1997   
869            870           499        1           2005        1994   
971            972           563        1           2005        2001   
...            ...           ...      ...            ...         ...   
13182687  13182688       7540834        1           2005        1988   
13182950  13182951       7541035        1           2005        2001   
13182973  13182974       7541061        1           2005        1997   
13183035  13183036       7541104        3           2005        1996   
13183794  13183795       7541716        2           2005        1998   

         Blind_Make Blind_Model Blind_Submodel Cat1 Cat2 Cat3 Cat4 Cat5 Cat6  \
274              BW        BW.5         BW.5.1    ?    ?    E    ?    ?    ?   
673              BW        BW.5         BW.5.1    ?    ?    E    ?    ?    ?   
678              BW        BW.5         BW.5.1    ?    ?    A    ?    ?    ?   
869              BW        BW.5         BW.5.1    ?    ?    C    ?    ?    ?   
971              BO       BO.67        BO.67.1    ?    A    A    ?    ?    ?   
...             ...         ...            ...  ...  ...  ...  ...  ...  ...   
13182687         BW       BW.65        BW.65.1    ?    ?    C    ?    ?    ?   
13182950         BW      BW.135       BW.135.1    ?    C    A    ?    ?    ?   
13182973         BW        BW.6         BW.6.1    ?    ?    A    ?    ?    ?   
13183035         BW        BW.6         BW.6.1    ?    ?    E    ?    ?    ?   
13183794         AH       AH.45        AH.45.1    ?    ?    A    ?    ?    ?   

         Cat7 Cat8 Cat9 Cat10 Cat11 Cat12 OrdCat      Var1      Var2  Var3  \
274         ?    A    B     A     A     B      5  3.496221  0.048405   0.0   
673         ?    B    B     A     B     B      5  3.496221  0.567140   0.0   
678         ?    B    B     B     A     B      5  3.496221  0.567140   0.0   
869         ?    A    B     B     A     C      5  3.496221  0.048405   0.0   
971         ?    A    B     A     A     F      5  2.146345  0.826507   0.0   
...       ...  ...  ...   ...   ...   ...    ...       ...       ...   ...   
13182687    ?    A    B     A     F     C      5  0.000000  0.134861   0.0   
13182950    ?    B    B     B     A     B      5  2.009750  1.950431   0.0   
13182973    ?    B    B     B     A     B      5  3.496221  0.999418   0.0   
13183035    ?    B    B     A     B     B      5  3.496221  1.085874   0.0   
13183794    ?    B    B     A     F     C      5  2.170450  0.999418   0.0   

              Var4  Var5      Var6  Var7  Var8 NVCat    NVVar1    NVVar2  \
274       0.316372   0.0  0.000000   0.0   0.0     K -0.231530 -0.266117   
673       0.485509   0.0  0.000000   0.0   0.0     M -0.231530 -0.266117   
678       0.654646   0.0  0.000000   0.0   0.0     M -0.231530 -0.266117   
869       0.316372   0.0  0.000000   0.0   0.0     K  2.054683 -0.266117   
971       0.739214   0.0  1.851846   0.0   0.0     L -0.231530 -0.266117   
...            ...   ...       ...   ...   ...   ...       ...       ...   
13182687  0.062666   0.0  0.000000   0.0   0.0     E -0.231530 -0.266117   
13182950  1.838605   0.0  2.215626   0.0   0.0     M -0.231530 -0.266117   
13182973  1.077488   0.0  0.000000   0.0   0.0     M -0.231530 -0.266117   
13183035  0.992920   0.0  0.000000   0.0   0.0     M -0.231530 -0.266117   
13183794  1.077488   0.0  0.000000   0.0   0.0     M -0.231530 -0.266117   

            NVVar3    NVVar4  Claim_Amount  
274      -0.272337  1.961988           0.0  
673      -0.272337 -0.251419           0.0  
678      -0.272337 -0.251419           0.0  
869      -0.272337 -0.251419           0.0  
971      -0.272337 -0.251419           0.0  
...            ...       ...           ...  
13182687 -0.272337 -0

In [7]:
raw_df[raw_df['Cat1'] =='?'].index

Int64Index([     274,      673,      678,      869,      971,     1112,
                1419,     1634,     2536,     2652,
            ...
            13180733, 13180884, 13181150, 13181172, 13182202, 13182687,
            13182950, 13182973, 13183035, 13183794],
           dtype='int64', length=25981)

In [8]:
for col in raw_df.columns:
    raw_df = raw_df.drop(raw_df[(raw_df[col] == '?')].index, axis= 0)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [9]:
raw_df

Row_ID  Household_ID  Vehicle  Calendar_Year  Model_Year  \
1                2             2        2           2005        2003   
6                7             4        1           2006        2001   
7                8             4        2           2006        2002   
8                9             4        3           2005        2002   
32              33            11        2           2005        2004   
...            ...           ...      ...            ...         ...   
13184260  13184261       7542085        2           2005        2001   
13184265  13184266       7542091        1           2005        2002   
13184273  13184274       7542097        3           2005        2005   
13184276  13184277       7542100        2           2005        2002   
13184279  13184280       7542103        1           2005        2003   

         Blind_Make Blind_Model Blind_Submodel Cat1 Cat2 Cat3 Cat4 Cat5 Cat6  \
1                 Q        Q.22         Q.22.3    B    C    A    A    A    E   
6                AJ      AJ.129       AJ.129.3    G    C    A    A    C    E   
7                AQ       AQ.17        AQ.17.1    B    C    B    A    A    D   
8                AQ       AQ.17        AQ.17.1    B    C    B    A    A    D   
32               AQ       AQ.17        AQ.17.2    B    C    B    A    A    D   
...             ...         ...            ...  ...  ...  ...  ...  ...  ...   
13184260          P         P.2          P.2.0    A    C    B    A    A    B   
13184265         AZ       AZ.21        AZ.21.0    B    B    B    A    A    C   
13184273          X        X.57         X.57.1    C    C    B    C    B    D   
13184276          Y        Y.34         Y.34.1    B    C    A    A    A    B   
13184279          K        K.40         K.40.3    E    A    A    A    A    C   

         Cat7 Cat8 Cat9 Cat10 Cat11 Cat12 OrdCat      Var1      Var2  \
1           C    A    B     A     B     D      5  0.217951  0.567140   
6           A    A    B     A     E     C      4  0.700049  0.221317   
7           C    B    A     A     C     B      4  0.017076  0.221317   
8           C    B    A     B     B     C      4  0.017076  0.221317   
32          C    B    A     B     A     C      4  0.017076  0.221317   
...       ...  ...  ...   ...   ...   ...    ...       ...       ...   
13184260    C    B    A     B     E     E      4 -0.553407  0.567140   
13184265    C    A    B     C     A     B      2 -1.011401  0.688177   
13184273    B    A    B     B     A     B      5 -0.384673  1.604608   
13184276    C    B    B     B     A     B      4 -0.400743 -0.297418   
13184279    A    B    B     B     A     B      2 -0.770352 -1.110101   

              Var3      Var4      Var5      Var6      Var7      Var8 NVCat  \
1         1.421206  0.485509  1.240851  0.432987 -0.726459  0.204785     O   
6         1.050960  0.147235  0.580718  0.551128  0.416289 -0.024395     M   
7         0.333610  0.231803  0.527193 -0.023200 -0.701884  0.226664     M   
8         0.333610  0.231803  0.527193 -0.023200 -0.701884  0.226664     M   
32        0.333610  0.231803  0.527193 -0.023200 -0.701884  0.390207     O   
...            ...       ...       ...       ...       ...       ...   ...   
13184260 -0.360600  0.485509 -0.055627 -0.250124 -0.959924  1.000624     M   
13184265 -0.915968  0.603904 -1.054747 -0.587000 -0.738747  0.286283     M   
13184273 -0.013495  1.500331 -0.287565  0.225948 -1.303977  1.690351     O   
13184276 -0.615144 -0.360176 -0.043732 -0.624431 -0.800185 -0.523230     M   
13184279 -0.499442 -1.036724 -1.179637 -1.061902 -0.259530 -0.727250     M   

           NVVar1    NVVar2    NVVar3    NVVar4  Claim_Amount  
1        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
6        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
7        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
8        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
32       -0.23153 -0.266117 -0.272337 -0.251419           0.0  


In [124]:
new_df.shape

Row_ID  Household_ID  Vehicle  Calendar_Year  Model_Year  \
0                1             1        3           2005        2005   
1                2             2        2           2005        2003   
2                3             3        1           2005        1998   
3                4             3        1           2006        1998   
4                5             3        2           2005        2001   
...            ...           ...      ...            ...         ...   
13184285  13184286       7542110        1           2005        1987   
13184286  13184287       7542111        1           2005        1989   
13184287  13184288       7542112        1           2005        1990   
13184288  13184289       7542112        2           2005        1998   
13184289  13184290       7542113        1           2005        1996   

         Blind_Make Blind_Model Blind_Submodel Cat1 Cat2 Cat3 Cat4 Cat5 Cat6  \
0                 K        K.78         K.78.2    D    C    F    ?    ?    C   
1                 Q        Q.22         Q.22.3    B    C    A    A    A    E   
2                AR       AR.41        AR.41.1    B    ?    A    A    A    C   
3                AR       AR.41        AR.41.1    B    ?    A    A    A    C   
4                 D        D.20         D.20.0    J    C    B    ?    ?    D   
...             ...         ...            ...  ...  ...  ...  ...  ...  ...   
13184285         BW      BW.156       BW.156.0    I    ?    C    ?    ?    E   
13184286         AJ      AJ.123       AJ.123.3    D    ?    C    ?    ?    C   
13184287          X        X.52         X.52.1    B    ?    D    A    A    C   
13184288          W         W.4          W.4.6    I    ?    A    ?    ?    C   
13184289          M        M.13         M.13.2    F    ?    A    C    A    C   

         Cat7 Cat8 Cat9 Cat10 Cat11 Cat12 OrdCat      Var1      Var2  \
0           ?    C    A     B     F     D      4  1.270533  0.999418   
1           C    A    B     A     B     D      5  0.217951  0.567140   
2           C    A    B     A     E     D      2 -0.754282 -1.646127   
3           C    A    B     B     B     B      2 -0.754282 -1.646127   
4           ?    A    B     A     B     B      5  0.563454  1.863975   
...       ...  ...  ...   ...   ...   ...    ...       ...       ...   
13184285    ?    A    B     A     B     E      5  1.407127  0.134861   
13184286    ?    A    B     C     A     C      4  1.045553 -0.816152   
13184287    C    A    B     A     B     B      2 -0.971226 -1.542380   
13184288    ?    A    B     B     A     D      4 -0.850702 -0.124506   
13184289    ?    A    B     B     A     B      2 -1.027471 -1.092810   

              Var3      Var4      Var5      Var6      Var7      Var8 NVCat  \
0         0.588154  0.908351  1.008912  0.261040  0.907793 -0.077998     M   
1         1.421206  0.485509  1.240851  0.432987 -0.726459  0.204785     O   
2        -1.101091 -1.679445 -0.971487 -1.405797 -0.837048 -1.176858     F   
3        -1.101091 -1.679445 -0.971487 -1.405797 -0.837048 -1.176858     F   
4         1.814591  1.838605  0.812656  2.112691  1.534462  2.347260     F   
...            ...       ...       ...       ...       ...       ...   ...   
13184285  1.745170  0.062666  1.663098  0.841216  1.141258 -0.986732     M   
13184286 -1.193652 -0.867587  0.093052 -0.203335  0.674329 -0.818812     M   
13184287 -0.869687 -1.577963 -0.840650 -1.169516 -1.205676 -1.451655     E   
13184288 -0.615144 -0.021902 -1.405628 -0.480556  0.145961 -0.191220     E   
13184289 -1.031670 -1.138207 -1.066641 -1.491186 -1.488291 -0.850317     O   

           NVVar1    NVVar2    NVVar3    NVVar4  Claim_Amount  
0        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
1        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
2        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
3        -0.23153 -0.266117 -0.272337 -0.251419           0.0  
4        -0.23153 -0.266117 -0.272337 -0.251419           0.0  


In [101]:
for col in raw_df.columns:
    new_raw_df = raw_df.drop(raw_df[raw_df[col] == '?'])

In [103]:
new_raw_df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[13184290 rows x 0 columns]

In [46]:
new_df= raw_df.drop(raw_df[(raw_df.Cat1 == '?')|\
                           (raw_df.Cat2 == '?')|\
                           (raw_df.Cat3 == '?')|\
                           (raw_df.Cat4 == '?')|\
                           (raw_df.Cat5 == '?')|\
                           (raw_df.Cat6 == '?')|\
                           (raw_df.Cat7 == '?')|\
                           (raw_df.Cat8 == '?')|\
                           (raw_df.Cat9 == '?')|\
                           (raw_df.Cat10 == '?')|\
                           (raw_df.Cat11 == '?')|\
                           (raw_df.Cat12 == '?')].index, axis =0, inplace = False)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [70]:
a =pd.DataFrame([[1,2,3],[1,2,'?'],[1,2,3],[1,2,3]])

In [71]:
a.columns =['1','2','3']

In [76]:
a.all()

AttributeError: 'DataFrame' object has no attribute 'item'

In [31]:
alpha = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
cate_num = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
for i in range(1,13):
    s = 'Cat'+ str(i)
    new_df[s].replace(alpha, cate_num, inplace=True)


In [42]:
new_df.shape

(3734697, 35)

In [8]:
import numpy as np

b =[[1.2,0.4],[0.4,1.2]]

In [16]:
b =np.array(b)
g = np.array([5.4,-7])

In [20]:
g.transpose()

array([ 5.4, -7. ])

In [12]:
b_in = np.linalg.inv(b)

In [21]:
np.dot(-b_in,g)

array([-7.25,  8.25])

In [59]:
b_k = np.array([[1.2,0.4],[0.4,1.2]])

In [60]:
z_k =  np.array([5.4,-7]).T - np.array([10,-20]).T

In [61]:
s_k = np.array([0.8,0.1]).T - np.array([-0.3,-0.7]).T

In [75]:
B = b_k + np.outer(z_k,z_k.T)/np.dot(z_k.T,s_k)\
    -np.outer(np.dot(b_k,s_k),np.dot(b_k,s_k).T)\
    /np.dot(np.dot(s_k.T,b_k),s_k)

In [76]:
B

array([[  4.24271098, -11.58372759],
       [-11.58372759,  32.17762544]])

In [77]:
inv_b = np.linalg.inv(B)

In [78]:
g = np.array([1,-1]).T

In [79]:
result = np.dot(-inv_b,g)

In [95]:
np.sum(result)

-11.950153600134792

In [73]:
result_ = -inv_b*g

In [67]:
result

array([-1.25,  1.25])

In [74]:
result_

array([[-0.63217971, -0.61782029],
       [ 0.61782029,  0.63217971]])

In [68]:
w =np.array([0.1,-0.8,2.3]).T

alpha = 0.3

In [69]:
np.sum(w)

1.5999999999999996

In [ ]:
0.01,0.64,5.29

In [70]:
rw = 0.3*3.2+(1-0.3)*1/2*5.94

In [71]:
rw

3.039

In [85]:
c = np.array([1,2,3,4,5])

In [86]:
np.dot(c, c.T)

55

In [94]:
-(3/7*np.log2(3/7)+1/7*np.log2(1/7)+2/7*np.log2(2/7)+1/7*np.log2(1/7))

1.8423709931771084